//! Validates the `find_peaks` port against real `scipy.signal.find_peaks`
//! output (fixtures under `fixtures/hifi/find_peaks/`, generated by
//! `scripts/hifi-fixtures/generate_find_peaks_reference.py`).

mod support;

use hifi_decode::{find_peaks, FindPeaksOptions};

fn fixture_path(name: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/hifi/find_peaks")
        .join(name)
}

struct Expected {
    peaks: Vec<usize>,
    left_ips: Vec<f64>,
    right_ips: Vec<f64>,
    prominences: Vec<f64>,
}

fn load_expected(name: &str) -> Expected {
    let text = std::fs::read_to_string(fixture_path(&format!("{name}_expected.json")))
        .unwrap_or_else(|e| panic!("failed to read {name}_expected.json: {e}"));
    let json: serde_json::Value = serde_json::from_str(&text).unwrap();
    let as_usize_vec = |key: &str| -> Vec<usize> {
        json[key].as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as usize).collect()
    };
    let as_f64_vec = |key: &str| -> Vec<f64> {
        json[key].as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect()
    };
    Expected {
        peaks: as_usize_vec("peaks"),
        left_ips: as_f64_vec("left_ips"),
        right_ips: as_f64_vec("right_ips"),
        prominences: as_f64_vec("prominences"),
    }
}

fn assert_matches(name: &str, options: FindPeaksOptions, ips_tol: f64, prom_tol: f64) {
    let x = support::load_f32(fixture_path(&format!("{name}_x.npy")));
    let expected = load_expected(name);

    let got = find_peaks(&x, options);

    let got_indices: Vec<usize> = got.iter().map(|p| p.index).collect();
    assert_eq!(got_indices, expected.peaks, "{name}: peak indices differ");

    for (i, peak) in got.iter().enumerate() {
        let d_left = (peak.left_ips - expected.left_ips[i]).abs();
        let d_right = (peak.right_ips - expected.right_ips[i]).abs();
        let d_prom = (peak.prominence - expected.prominences[i]).abs();
        assert!(d_left < ips_tol, "{name} peak {i}: left_ips {} vs {} (diff {d_left})", peak.left_ips, expected.left_ips[i]);
        assert!(d_right < ips_tol, "{name} peak {i}: right_ips {} vs {} (diff {d_right})", peak.right_ips, expected.right_ips[i]);
        assert!(d_prom < prom_tol, "{name} peak {i}: prominence {} vs {} (diff {d_prom})", peak.prominence, expected.prominences[i]);
    }
}

#[test]
fn sparse_spikes_distance_matches_scipy() {
    assert_matches(
        "sparse_spikes_distance",
        FindPeaksOptions {
            distance: Some(50.0),
            threshold_min: None,
            prominence_min: None,
        },
        1e-3,
        1e-3,
    );
}

#[test]
fn neighbor_search_matches_scipy() {
    assert_matches(
        "neighbor_search",
        FindPeaksOptions {
            distance: Some(1.0),
            threshold_min: Some(0.5),
            prominence_min: Some(0.25),
        },
        1e-3,
        1e-3,
    );
}
